"""gauss_flows — JAX/FlowJax-based RBIG and Gaussianization flows.

Public API re-exported from the private _src/ implementation directory.
"""

from __future__ import annotations

from gauss_flows._src.conditioning import (
    pack_time_control,
    time_control_cond_shape,
    unpack_time_control,
)
from gauss_flows._src.distributions import (
    GaussianMixture,
    GaussianPCA,
    UniformOnSphere,
    VonMisesFisher,
)
from gauss_flows._src.flows import (
    SurVAEFlow,
    coupling_gaussianization_flow,
    gaussianization_flow,
    iterative_rbig,
)
from gauss_flows._src.inference import FlowDist, FlowGuide, fit_gaussianization_flow
from gauss_flows._src.init import fit_rbig, fit_rbig_coupling
from gauss_flows._src.info_theory import (
    entropy,
    kl_divergence,
    mutual_information,
    negentropy,
    total_correlation,
)
from gauss_flows._src.nn import TimeFourier, TimeIdentity, TimeTanh
from gauss_flows._src.transforms import (
    VAE,
    ActNorm,
    ActNorm1D,
    AffineCoupling,
    Augment,
    BatchNorm,
    CircularRationalQuadraticSpline,
    CircularRQSplineCoupling,
    ContinuousAffineCoupling,
    DeepSigmoidCoupling,
    FixedRotation,
    HaarWavelet,
    HistogramCDF,
    HouseholderRotation,
    InverseGaussCDF,
    Invertible1x1Conv,
    LULinearPermute,
    MixtureGaussianCDF,
    MixtureGaussianCDFCoupling,
    MixtureLogisticCDF,
    Orthogonal1x1Conv,
    OrthogonalConvExponential,
    OrthogonalRotation,
    PeriodicShift,
    PeriodicWrap,
    PlanarFlow,
    RQSplineCoupling,
    RQSplineMarginal,
    SimpleAbsSurjection,
    SimpleMaxPoolSurjection2d,
    SimpleSortSurjection,
    Slice,
    Squeeze,
    StochasticPermutation,
    SylvesterFlow,
    expmap_sphere,
    logmap_sphere,
    tangent_basis,
)
from gauss_flows._src.transforms.base import AbstractStochastic, AbstractSurjection


__all__ = [
    "VAE",
    "AbstractStochastic",
    "AbstractSurjection",
    "ActNorm",
    "ActNorm1D",
    "AffineCoupling",
    "Augment",
    "BatchNorm",
    "CircularRQSplineCoupling",
    "CircularRationalQuadraticSpline",
    "ContinuousAffineCoupling",
    "DeepSigmoidCoupling",
    "FixedRotation",
    "FlowDist",
    "FlowGuide",
    "GaussianMixture",
    "GaussianPCA",
    "HaarWavelet",
    "HistogramCDF",
    "HouseholderRotation",
    "InverseGaussCDF",
    "Invertible1x1Conv",
    "LULinearPermute",
    "MixtureGaussianCDF",
    "MixtureGaussianCDFCoupling",
    "MixtureLogisticCDF",
    "Orthogonal1x1Conv",
    "OrthogonalConvExponential",
    "OrthogonalRotation",
    "PeriodicShift",
    "PeriodicWrap",
    "PlanarFlow",
    "RQSplineCoupling",
    "RQSplineMarginal",
    "SimpleAbsSurjection",
    "SimpleMaxPoolSurjection2d",
    "SimpleSortSurjection",
    "Slice",
    "Squeeze",
    "StochasticPermutation",
    "SurVAEFlow",
    "SylvesterFlow",
    "TimeFourier",
    "TimeIdentity",
    "TimeTanh",
    "UniformOnSphere",
    "VonMisesFisher",
    "coupling_gaussianization_flow",
    "entropy",
    "expmap_sphere",
    "fit_gaussianization_flow",
    "fit_rbig",
    "fit_rbig_coupling",
    "gaussianization_flow",
    "iterative_rbig",
    "kl_divergence",
    "logmap_sphere",
    "mutual_information",
    "negentropy",
    "pack_time_control",
    "tangent_basis",
    "time_control_cond_shape",
    "total_correlation",
    "unpack_time_control",
]
